import{a as b,S as q,i as d}from"./assets/vendor-tnUJPedx.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))s(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function n(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(r){if(r.ep)return;r.ep=!0;const o=n(r);fetch(r.href,o)}})();const w="49000091-3868361750e1c7c48df9380e6",v="https://pixabay.com/api/",M=40;async function f(t,e=1){if(!t.trim())throw new Error("Search query is empty!");const n={key:w,q:encodeURIComponent(t),image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:M};try{return(await b.get(v,{params:n})).data}catch(s){throw console.error("Error fetching images:",s),s}}function g(t,e=!1){const n=document.querySelector(".gallery");e||(n.innerHTML="");const s=t.map(({webformatURL:r,largeImageURL:o,tags:i,likes:L,views:E,comments:P,downloads:S})=>`
        <div class="image-item">
            <a href="${o}" class="gallery-item">
                <img src="${r}" alt="${i}" />
            </a>
            <div class="metadata">
                <span>Likes: ${L}</span>
                <span>Views: ${E}</span>
                <span>Comments: ${P}</span>
                <span>Downloads: ${S}</span>
            </div>
        </div>
    `).join("");n.insertAdjacentHTML("beforeend",s),new q(".gallery a").refresh()}function m(t){const e=document.querySelector(".error-message");e.textContent=t,e.style.display="block"}function p(){document.querySelector("#loader").style.display="block"}function u(){document.querySelector("#loader").style.display="none"}function y(t){const e=document.querySelector("#load-more");e.style.display=t?"block":"none"}const x=document.querySelector("#search-form"),$=document.querySelector("#search"),A=document.querySelector(".gallery"),a=document.createElement("button");a.id="load-more";a.textContent="Load more";a.style.display="none";a.style.margin="20px auto";a.style.padding="10px 20px";a.style.border="none";a.style.cursor="pointer";document.body.appendChild(a);let l="",c=1;const h=40;x.addEventListener("submit",async t=>{if(t.preventDefault(),l=$.value.trim(),!l){d.error({title:"Error",message:"Please enter a search query!"});return}c=1,A.innerHTML="",y(!1),p();try{const e=await f(l,c);u(),e.hits.length===0?m("Sorry, there are no images matching your search query. Please try again!"):(g(e.hits),e.totalHits>h&&y(!0))}catch{u(),m("Failed to fetch images. Please try again later."),d.error({title:"Error",message:"Failed to fetch images. Please try again later."})}});a.addEventListener("click",async()=>{c+=1,p();try{const t=await f(l,c);u(),g(t.hits,!0);const e=Math.ceil(t.totalHits/h);c>=e&&(y(!1),d.info({title:"Info",message:"We're sorry, but you've reached the end of search results."})),I()}catch{u(),m("Failed to fetch more images. Please try again later."),d.error({title:"Error",message:"Failed to fetch more images. Please try again later."})}});function I(){const t=document.querySelectorAll(".image-item");if(t.length>0){const e=t[0].getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
